[programs.localnet]
junkyard = "8D5otLJfcwNyNd7iEHk3zcmRH1RPmYWqAkaCYQLmtbLu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/aaronly/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
